export const mockPresalesCustomers = {
  user_feng: {
    id: "user_feng",
    name: "Feng Liu",
    businessName: "Maple Retail LLC",
    customerType: "sme",
    city: "Jersey City",
    industry: "retail",
    businessAgeMonths: 38,
    annualRevenueCents: 86000000,
    riskTier: "low",
    phone: "+1-201-555-0188",
    email: "feng@example.com",
    contactPermission: true,
  },
  user_maya: {
    id: "user_maya",
    name: "Maya Chen",
    businessName: "Northstar Studio LLC",
    customerType: "sme",
    city: "Newark",
    industry: "creative_services",
    businessAgeMonths: 8,
    annualRevenueCents: 12000000,
    riskTier: "medium",
    phone: "+1-973-555-0109",
    email: "maya@example.com",
    contactPermission: true,
  },
  user_risk: {
    id: "user_risk",
    name: "Jordan Smith",
    businessName: "Harbor Wholesale LLC",
    customerType: "sme",
    city: "Hoboken",
    industry: "wholesale",
    businessAgeMonths: 20,
    annualRevenueCents: 19000000,
    riskTier: "high",
    phone: "+1-201-555-0119",
    email: "jordan@example.com",
    contactPermission: true,
  },
};

export const mockExistingRelationships = {
  user_feng: {
    userId: "user_feng",
    businessChecking: true,
    merchantServices: true,
    existingLoanBalanceCents: 0,
    priorDelinquencies: 0,
    relationshipMonths: 31,
  },
  user_maya: {
    userId: "user_maya",
    businessChecking: false,
    merchantServices: false,
    existingLoanBalanceCents: 0,
    priorDelinquencies: 0,
    relationshipMonths: 2,
  },
  user_risk: {
    userId: "user_risk",
    businessChecking: true,
    merchantServices: false,
    existingLoanBalanceCents: 4500000,
    priorDelinquencies: 2,
    relationshipMonths: 12,
  },
};

export const mockPresalesProducts = [
  {
    id: "prod_working_capital_plus",
    name: "经营周转贷",
    category: "term_loan",
    useCases: ["working_capital", "inventory"],
    minAmountCents: 5000000,
    maxAmountCents: 25000000,
    minTermMonths: 6,
    maxTermMonths: 24,
    minBusinessAgeMonths: 12,
    minAnnualRevenueCents: 20000000,
    aprRangeBps: { min: 850, max: 1450 },
    summary: "适合已有稳定流水的小微企业补充经营周转资金。",
    requiredDocuments: ["近 6 个月银行流水", "企业注册文件", "近一年税表或财务报表"],
    fees: ["可能收取 1%-2% 发放服务费，具体以审批为准"],
  },
  {
    id: "prod_starter_microline",
    name: "小微启航额度",
    category: "credit_line",
    useCases: ["working_capital", "inventory", "expansion"],
    minAmountCents: 500000,
    maxAmountCents: 5000000,
    minTermMonths: 3,
    maxTermMonths: 12,
    minBusinessAgeMonths: 6,
    minAnnualRevenueCents: 6000000,
    aprRangeBps: { min: 1200, max: 1900 },
    summary: "适合经营时间较短或金额较小的周转需求。",
    requiredDocuments: ["企业注册文件", "近 3 个月银行流水", "经营场地或销售证明"],
    fees: ["额度使用费和提款利息以实际合同为准"],
  },
  {
    id: "prod_equipment_finance",
    name: "设备融资方案",
    category: "equipment_finance",
    useCases: ["equipment"],
    minAmountCents: 2500000,
    maxAmountCents: 50000000,
    minTermMonths: 12,
    maxTermMonths: 60,
    minBusinessAgeMonths: 24,
    minAnnualRevenueCents: 25000000,
    aprRangeBps: { min: 700, max: 1350 },
    summary: "适合购买设备、机器或经营车辆等固定资产。",
    requiredDocuments: ["设备报价单", "近 6 个月银行流水", "企业注册文件", "设备供应商信息"],
    fees: ["可能存在评估费或抵押登记费，视设备类型而定"],
  },
  {
    id: "prod_invoice_bridge",
    name: "发票回款周转",
    category: "credit_line",
    useCases: ["invoice_bridge", "working_capital"],
    minAmountCents: 1000000,
    maxAmountCents: 15000000,
    minTermMonths: 1,
    maxTermMonths: 6,
    minBusinessAgeMonths: 12,
    minAnnualRevenueCents: 15000000,
    aprRangeBps: { min: 950, max: 1600 },
    summary: "适合已有应收账款、需要短期垫资的企业。",
    requiredDocuments: ["应收发票或合同", "买方付款记录", "近 6 个月银行流水"],
    fees: ["按提款天数和发票质量综合定价"],
  },
];
